/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0-dev3
 *
 * Project: 'hello_world_demo_cm4+helloworlddemocm4_release' 
 * Target:  'helloworlddemocm4_release' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "fsl_device_registers.h"



#endif /* RTE_COMPONENTS_H */
